version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - 2000:5432
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    restart: always
    ports:
      - 2001:6379
    volumes:
      - redis:/var/lib/redis

volumes:
  redis:
  db: