version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - 2000:5432
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    restart: always
    ports:
      - 2001:6379
    volumes:
      - redis:/var/lib/redis
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 2002:27017
    volumes:
      - mongo:/data/db


#  backend_project:
#    build: ./
#    image: backend_project_image
#    container_name: backend_project_container
#    environment:
#      AWS_ACCESS_KEY_ID: AKIAVUQ57EQQRAA3676N
#      AWS_SECRET_ACCESS_KEY: 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
#    ports:
#      - 8081:8081
#    deploy:
#      mode: replicated
#      replicas: 2

volumes:
  redis:
  db:
  mongo: